# Generated by Django 4.1.5 on 2023-01-25 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("travello", "0015_auto_20200516_1003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactions",
            name="Date_Time",
            field=models.CharField(
                default=datetime.datetime(
                    2023, 1, 25, 23, 3, 58, 527550, tzinfo=datetime.timezone.utc
                ),
                max_length=19,
            ),
        ),
    ]
