# Generated by Django 4.1.5 on 2023-01-29 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0020_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 1, 29, 20, 1, 42, 137309, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
