# Generated by Django 4.1.6 on 2023-02-04 04:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0021_alter_transactions_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='Date_Time',
            field=models.CharField(default=datetime.datetime(2023, 2, 4, 4, 41, 24, 858933, tzinfo=datetime.timezone.utc), max_length=19),
        ),
    ]
